# Generated by Django 3.2.16 on 2022-11-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0002_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='number',
            new_name='product_code_number',
        ),
    ]
