# Generated by Django 3.2.16 on 2022-11-07 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0005_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_stock',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr'), ('MISS', 'Miss'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('DR', 'Dr')], max_length=20),
        ),
    ]
