# Generated by Django 3.2.16 on 2022-11-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0007_alter_customer_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[(1, 'Achham'), (2, 'Arghakhanchi'), (3, 'Baglung'), (4, 'Baitadi'), (5, 'Bajhang'), (6, 'Bajura'), (7, 'Banke'), (8, 'Bara'), (9, 'Bardiya'), (10, 'Bhaktapur'), (11, 'Bhojpur'), (12, 'Chitwan'), (13, 'Dadeldhura'), (14, 'Dailekh'), (15, 'Dang deukhuri'), (16, 'Darchula'), (17, 'Dhading'), (18, 'Dhankuta'), (19, 'Dhanusa'), (20, 'Dholkha'), (21, 'Dolpa'), (22, 'Doti'), (23, 'Gorkha'), (24, 'Gulmi'), (25, 'Humla'), (26, 'Ilam'), (27, 'Jajarkot'), (28, 'Jhapa'), (29, 'Jumla'), (30, 'Kailali'), (31, 'Kalikot'), (32, 'Kanchanpur'), (33, 'Kapilvastu'), (34, 'Kaski'), (35, 'Kathmandu'), (36, 'Kavrepalanchok'), (37, 'Khotang'), (38, 'Lalitpur'), (39, 'Lamjung'), (41, 'Makwanpur'), (42, 'Manang'), (40, 'Mahottari'), (43, 'Morang'), (44, 'Mugu'), (45, 'MustMang'), (46, 'Myagdi'), (47, 'Nawalparasi'), (48, 'Nuwakot'), (49, 'Okhaldhunga'), (50, 'Palpa'), (51, 'Panchthar'), (52, 'Parbat'), (53, 'Parsa'), (54, 'Pyuthan'), (55, 'Ramechhap'), (56, 'Rasuwa'), (57, 'Rautahat'), (58, 'Rolpa'), (59, 'Rukum'), (60, 'Rupandehi'), (61, 'Salyan'), (62, 'Sankhuwasabha'), (63, 'Saptari'), (64, 'Sarlahi'), (65, 'Sindhuli'), (66, 'Sindhupalchok'), (67, 'Siraha'), (68, 'Solukhumbu'), (69, 'Sunsari'), (70, 'Surkhet'), (71, 'Syangja'), (72, 'Tanahu'), (73, 'Taplejung'), (74, 'Terhathum'), (75, 'Udayapur')], max_length=30),
        ),
    ]
