# Generated by Django 3.2.16 on 2022-11-07 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0008_alter_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Province',
            field=models.CharField(choices=[(1, 'Bagmati'), (2, 'Bheri'), (3, 'Dhawalagiri'), (4, 'Gandaki'), (5, 'Janakpur'), (6, 'Karnali'), (7, 'Koshi'), (8, 'Lumbini'), (9, 'Mahakali'), (10, 'Mechi'), (11, 'Narayani'), (12, 'Rapti'), (13, 'Sagarmatha'), (14, 'Seti')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
