# Generated by Django 3.2.16 on 2022-11-07 14:17

from django.db import migrations, models
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0009_customer_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Post_Zip_code',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
