# Generated by Django 3.2.16 on 2022-11-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catlog', '0011_auto_20221107_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
